# Your Name or Company
title: Evelyn Máire

# Description of your website. This is used for social sharing.
description:  Web-card of Evelyn Máire.

# A brief blurb about yourself
content: >-
  Finalist student studying at the University of Otago with an interest in Asian religion and culture, and Japanese language.  
>-
  Hobbyist coder since Neopets ✌️

# Add your social links
social:
  - platform: github
    url: https://github.com/evelynmaire
  - platform: linkedin
    url: https://www.linkedin.com/in/evelynmaire/

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni"
markdown: kramdown
sharing_image: share.jpg
#google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
